services:
  postgres:
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - bs_int-data:/tmp/static
      - image-data:/images-dir
    networks:
      - bs_int-backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  bs_int:
    environment:
      - DJANGO_SETTINGS_MODULE=bs_int.site.prod_settings
    restart: unless-stopped
