[project]
name = "bs-int"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.0.3",
    "django-extensions>=4.1",
    "gunicorn>=23.0.0",
    "matplotlib>=3.10.3",
    "openpyxl>=3.1.5",
    "pillow>=11.2.1",
    "psycopg2",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "bpython>=0.25",
    "django-silk>=5.4.0",
    "isort>=6.0.1",
    "pdbpp>=0.11.6",
    "pytest>=8.4.1",
    "pytest-django>=4.11.1",
    "pytest-mock>=3.14.1",
    "pytest-socket>=0.7.0",
]
