# Generated by Django 5.0.3 on 2024-04-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TreasuryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("one_month", models.FloatField(null=True)),
                ("two_month", models.FloatField(null=True)),
                ("three_month", models.FloatField(null=True)),
                ("four_month", models.FloatField(null=True)),
                ("six_month", models.FloatField(null=True)),
                ("one_year", models.FloatField(null=True)),
                ("two_year", models.FloatField(null=True)),
                ("three_year", models.FloatField(null=True)),
                ("five_year", models.FloatField(null=True)),
                ("seven_year", models.FloatField(null=True)),
                ("ten_year", models.FloatField(null=True)),
                ("twenty_year", models.FloatField(null=True)),
                ("thirty_year", models.FloatField(null=True)),
                ("loaded", models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name="treasurydata",
            constraint=models.UniqueConstraint(models.F("date"), name="unique_date"),
        ),
    ]
