# Generated by Django 5.0.3 on 2024-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TreasuryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("one_month", models.FloatField(editable=False, null=True)),
                ("two_month", models.FloatField(editable=False, null=True)),
                ("three_month", models.FloatField(editable=False, null=True)),
                ("four_month", models.FloatField(editable=False, null=True)),
                ("six_month", models.FloatField(editable=False, null=True)),
                ("one_year", models.FloatField()),
                ("two_year", models.FloatField()),
                ("three_year", models.FloatField()),
                ("five_year", models.FloatField()),
                ("seven_year", models.FloatField()),
                ("ten_year", models.FloatField()),
                ("twenty_year", models.FloatField()),
                ("thirty_year", models.FloatField()),
                (
                    "chart",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="uploads/%Y/%m/%d/",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Treasury Data",
            },
        ),
        migrations.AddConstraint(
            model_name="treasurydata",
            constraint=models.UniqueConstraint(models.F("date"), name="unique_date"),
        ),
    ]
