# Generated by Django 5.0.3 on 2024-04-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="treasurydata",
            options={"verbose_name_plural": "Treasury Data"},
        ),
    ]
