# Generated by Django 5.0.3 on 2024-04-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = []
