# Generated by Django 5.0.3 on 2024-04-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0002_alter_treasurydata_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treasurydata",
            name="loaded",
        ),
    ]
