# Generated by Django 5.0.3 on 2024-04-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0003_remove_treasurydata_loaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="treasurydata",
            name="chart",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
