# Generated by Django 5.0.3 on 2024-04-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0004_treasurydata_chart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treasurydata",
            name="chart",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="uploads/%Y/%m/%d/"
            ),
        ),
    ]
