# Generated by Django 5.0.3 on 2024-04-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rates", "0005_alter_treasurydata_chart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treasurydata",
            name="four_month",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="treasurydata",
            name="one_month",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="treasurydata",
            name="six_month",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="treasurydata",
            name="three_month",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="treasurydata",
            name="two_month",
            field=models.FloatField(editable=False, null=True),
        ),
    ]
