name: 'Test'

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: make tests

      - name: Check migrations
        run: make check-migrations

      - name: Check Ruff linting
        run: make check-ruff

      - name: Check Black linting
        run: make check-black

      - name: Check isort linting
        run: make check-isort
